import React from "react";

const Terms = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-10 mt-20 text-gray-800 dark:text-white">
      <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>
      <p className="mb-4">Effective Date: August 2, 2025</p>

      <p className="mb-6">
        Welcome to RemindrAI! These Terms and Conditions ("Terms") govern your
        use of our SaaS application and all related services, available at
        **remindrai.app**. By accessing or using our service, you agree to be
        bound by these Terms.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        1. Acceptance of Terms
      </h2>
      <p className="mb-4">
        You must be at least **18 years of age** to use RemindrAI. By creating
        an account, you represent and warrant that you meet this age requirement
        and have the full right and authority to enter into this agreement. If
        you do not agree to these Terms, you may not use the service.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">2. Your Account</h2>
      <p className="mb-4">
        You are responsible for maintaining the confidentiality of your account
        password and for all activities that occur under your account. You agree
        to notify us immediately of any unauthorized use of your account. We
        reserve the right to suspend or terminate your account at our sole
        discretion if we suspect a violation of these Terms.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">3. Your Content</h2>
      <p className="mb-4">
        RemindrAI allows you to create and schedule content for your social
        media platforms. You retain full ownership of all intellectual property
        rights in the content you create and post through our service ("Your
        Content"). However, by using the service, you grant us a limited,
        non-exclusive, royalty-free license to use, display, and process Your
        Content solely for the purpose of providing the RemindrAI service to
        you. You represent and warrant that Your Content does not violate any
        third-party rights.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">4. Prohibited Conduct</h2>
      <p className="mb-4">
        You agree not to use the RemindrAI service for any unlawful or
        prohibited activities, including but not limited to: posting or
        transmitting illegal content, attempting to interfere with the service's
        functionality, or reverse engineering any part of the service.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        5. AI-Generated Content
      </h2>
      <p className="mb-4 text-yellow-700 font-medium">
        When AI content generation features are introduced, you acknowledge that
        any content generated by the AI is a draft. We make no guarantees
        regarding the accuracy, quality, or suitability of AI-generated content.
        You are responsible for reviewing and using AI outputs at your
        discretion.
        <strong> [Update Coming Soon]</strong>
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        6. Disclaimers and Limitation of Liability
      </h2>
      <p className="mb-4">
        RemindrAI is provided "as is" and "as available," without any warranties
        of any kind. To the maximum extent permitted by law, we shall not be
        liable for any indirect, incidental, special, consequential, or punitive
        damages, or any loss of profits or revenues, resulting from your use of
        the service. Our total liability to you shall not exceed the amount you
        have paid us in the last six (6) months for the service.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        7. Governing Law and Jurisdiction
      </h2>
      <p className="mb-4">
        These Terms shall be governed by and construed in accordance with the
        laws of **India**. Any disputes arising from these Terms will be subject
        to the exclusive jurisdiction of the courts located in India.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">8. Changes to Terms</h2>
      <p className="mb-4">
        We reserve the right to modify these Terms at any time. We will notify
        you of any significant changes by email or an in-app notification. By
        continuing to use the service after the changes are effective, you agree
        to be bound by the revised Terms.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">9. Contact</h2>
      <p className="mb-4">
        For questions about these Terms & Conditions, please email
        <a
          href="mailto:remindraiapp@gmail.com"
          className="text-blue-600 underline ml-1"
        >
          remindraiapp@gmail.com
        </a>
        .
      </p>
    </div>
  );
};

export default Terms;
