// src/pages/Dashboard/OverviewUI/RemindersKpi.jsx
import React from "react";

function KpiCard({ label, value, hint, accent = "blue" }) {
  const accentColor =
    {
      blue: "text-blue-400",
      green: "text-green-400",
      yellow: "text-yellow-400",
      purple: "text-purple-400",
    }[accent] || "text-blue-400";

  return (
    <div className="flex flex-col justify-between bg-[#111827] dark:bg-[#0f172a] rounded-xl p-5 w-full sm:w-56 shadow-sm hover:shadow-md transition">
      <div className="text-xs text-gray-400 uppercase tracking-wide">
        {label}
      </div>
      <div
        className={`text-3xl font-semibold mt-1 ${accentColor}`}
        aria-label={label}
      >
        {value ?? "—"}
      </div>
      {hint && <div className="text-xs text-gray-500 mt-2">{hint}</div>}
    </div>
  );
}

/**
 * InsightKpi
 * ---------------------------------------------------------------------------
 * Reflects the creative heartbeat of RemindrAI — not scheduling,
 * but how consistently your AI is helping you create.
 *
 * Categories:
 * - AI Drafts → Proactive content ideas generated by AI
 * - Manual Notes → Personal entries you’ve added
 * - Active Creations → Currently running AI content workflows
 * - Delivered Drafts → Content that’s already been generated
 */
export default function RemindersKpi({
  aiCount = 0,
  simpleCount = 0,
  activeCount = 0,
  completedCount = 0,
}) {
  const kpis = [
    {
      label: "AI Drafts",
      value: aiCount,
      hint: "Fresh, on-brand content ideas generated by your AI",
      accent: "blue",
    },
    {
      label: "Manual Notes",
      value: simpleCount,
      hint: "Your own saved ideas and inspirations",
      accent: "purple",
    },
    {
      label: "Active Creations",
      value: activeCount,
      hint: "AI workflows currently preparing new drafts for you",
      accent: "green",
    },
    {
      label: "Delivered Drafts",
      value: completedCount,
      hint: "Ideas and posts already generated and ready to refine",
      accent: "yellow",
    },
  ];

  return (
    <section className="mt-8 flex flex-col sm:flex-row flex-wrap gap-4">
      {kpis.map((kpi) => (
        <KpiCard key={kpi.label} {...kpi} />
      ))}
    </section>
  );
}
